const mongoose = require('mongoose');

// the room id is autogenerated in mongodb
const roomSchema = mongoose.Schema({
    'ClientId' : { // client's id under the users model
        type: String,
        required: true
    },
    'TherapistId' : { // therapist's id under the users model
        type: String,
        required: true
    },
    'Status': {
        type: String,
        default: "active"
    },
    'Potential_Cases': {
        type: Array,
        require: true
    }
}, { timestamps: true });

const roomModel = mongoose.model('room', roomSchema);
module.exports = roomModel;